"""add progress tracking to scrape_runs

Revision ID: 4b1588f5a0b0
Revises: 1c684c4c080a
Create Date: 2026-04-05 18:47:51.574435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b1588f5a0b0'
down_revision: Union[str, Sequence[str], None] = '1c684c4c080a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_runs', sa.Column('stage', sa.String(length=30), nullable=True))
    op.add_column('scrape_runs', sa.Column('progress_current', sa.Integer(), nullable=True))
    op.add_column('scrape_runs', sa.Column('progress_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_runs', 'progress_total')
    op.drop_column('scrape_runs', 'progress_current')
    op.drop_column('scrape_runs', 'stage')
    # ### end Alembic commands ###
