"""add classified_at to job_postings

Revision ID: 86b85e8ce105
Revises: 4b1588f5a0b0
Create Date: 2026-04-05 20:47:16.148059

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "86b85e8ce105"
down_revision: str | Sequence[str] | None = "4b1588f5a0b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job_postings", sa.Column("classified_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_postings", "classified_at")
    # ### end Alembic commands ###
